// client/react-front/src/components/Item.jsx
import React, { useState } from "react";

export default function Item({
  title,
  isComplete,
  id,
  handleStatusChange,
  handleTitleChange,
  handleDelete,
}) {
  const [isEdit, setIsEdit] = useState(false);
  const [newTitle, setNewTitle] = useState(title);
  return (
    <li className="item">
      <div
        job="complete"
        id="0"
        onClick={(e) => handleStatusChange(id, !isComplete)}
      >
        {isComplete ? (
          <i className="fas fa-check-circle"></i>
        ) : (
          <i className="fas fa-circle"></i>
        )}
      </div>
      {isEdit ? (
        <>
          <input
            placeholder={title}
            className="text"
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
          />
          <i
            className="fas fa-spell-check"
            onClick={(e) => {
              handleTitleChange(id, newTitle);
              setIsEdit(!isEdit);
            }}
          ></i>
          <i className="fas fa-ban" onClick={(e) => setIsEdit(!isEdit)}></i>
        </>
      ) : (
        <p className="text">{title}</p>
      )}
      {!isEdit && (
        <i
          className="fas fa-edit"
          job="delete"
          id="0"
          onClick={(e) => setIsEdit(!isEdit)}
        ></i>
      )}
      <i
        className="far fa-trash-alt"
        job="delete"
        id="0"
        onClick={(e) => handleDelete(id)}
      ></i>
    </li>
  );
}

// client/angular-front/src/app/components/item/item.component.ts
import { Component, OnInit, Input, EventEmitter, Output } from "@angular/core";
import { Todo } from "src/app/models/Todo";
import { TodoService } from "../../services/todo.service";
import { FormControl } from "@angular/forms";

@Component({
  selector: "app-item",
  templateUrl: "./item.component.html",
  styleUrls: ["./item.component.css"],
})
export class ItemComponent implements OnInit {
  @Input("todo") todo: Todo;
  @Output() delete: EventEmitter<any> = new EventEmitter();
  @Output() change: EventEmitter<any> = new EventEmitter();
  isEdit = false;
  title = new FormControl("");

  constructor(private todoservice: TodoService) {}

  ngOnInit(): void {}

  setEdit() {
    this.isEdit = !this.isEdit;
  }

  handleStatusChange() {
    this.todoservice
      .update(this.todo._id, !this.todo.completed, "")
      .subscribe((res) => {
        console.log("res", res);
        this.change.emit(res);
      });
  }

  handleTitleChange() {
    this.todoservice
      .update(this.todo._id, "", this.title.value)
      .subscribe((res) => {
        this.change.emit(res);
        this.isEdit = false;
      });
  }

  handleDelete() {
    this.todoservice.delete(this.todo._id).subscribe((res) => {
      console.log("res", res);
      this.delete.emit(res);
    });
  }
}

<li *ngIf="todo" class="item">
  <div job="complete" id="0" (click)="handleStatusChange()">
    <i *ngIf="todo['completed']" class="fas fa-check-circle"></i>
    <i *ngIf="!todo['completed']" class="fas fa-circle"></i>
  </div>
  <input *ngIf="isEdit" class="text" [formControl]="title" />
  <i
    *ngIf="isEdit"
    class="fas fa-spell-check"
    (click)="handleTitleChange()"
  ></i>
  <i *ngIf="isEdit" class="fas fa-ban" (click)="setEdit()"></i>
  <p *ngIf="!isEdit" class="text" #TitleBlock>{{ todo["title"] }}</p>
  <i
    *ngIf="!isEdit"
    class="fas fa-edit"
    job="delete"
    id="0"
    (click)="setEdit()"
  ></i>
  <i class="far fa-trash-alt" job="delete" id="0" (click)="handleDelete()"></i>
</li>
