// client/react-front/tmp/pages/Home.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = Home;

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function Home() {
  return /*#__PURE__*/_react.default.createElement("div", {
    className: "about",
    style: {
      padding: "20px",
      backgroundColor: "#007bff",
      color: "white",
      borderRadius: "0.25rem"
    }
  }, /*#__PURE__*/_react.default.createElement("div", {
    className: "inner-about"
  }, /*#__PURE__*/_react.default.createElement("h1", null, "React todo app"), /*#__PURE__*/_react.default.createElement("br", null), /*#__PURE__*/_react.default.createElement("p", null, "Welcome to the react version of your favourite todo app")));
}

// client/vue-front/src/pages/Home.vue
 <template>
  <div class="about">
    <div class="inner-about">
      <h1>Vue todo app</h1>
      <br>
      <p>Welcome to the vue version of your favourite todo app</p>
    </div>
  </div>
</template>

<script type="text/javascript">
export default {
  name: "home"
};
</script>
<style scoped>
.about {
  background-color: #54a041;
  padding: 20px;
  color: white;
  border-radius: 0.25rem;
}
.inner-about {
  width: 100%;
  max-width: 600pt;
  padding: 10pt;
}
.inner-about h1 {
  margin: 0;
  font-size: 35pt;
  margin-bottom: -10pt;
}
.inner-about p {
  margin: 0;
  margin-bottom: 8pt;
  font-size: 15pt;
}
</style>
