// client/react-front/src/pages/Todo.jsx
import React, { useState, useEffect } from "react";
import "../styles/todo.css";
import api from "../api/todo";
import Add from "../components/Add";
import Item from "../components/Item";

export default function Todo({ username }) {
  const [todos, settodos] = useState([]);
  useEffect(() => {
    const res = api.getAll().then((_todos) => {
      console.log("_todos", _todos);
      settodos(_todos.todos);
    });

    return () => {};
  }, []);

  function handleDelete(id) {
    console.log("id", id);
    api.delete(id).then((res) => {
      console.log("delete done", res);
      settodos(todos.filter((todo) => todo._id !== id));
    });
  }

  function handleStatusChange(id, status) {
    settodos(
      todos.map((todo) => {
        if (todo._id === id) todo.completed = !todo.completed;
        return todo;
      })
    );
    api.update(id, status, "").then((res) => {
      console.log("status change done", res);
    });
  }

  function handleTitleChange(id, title) {
    settodos(
      todos.map((todo) => {
        if (todo._id === id) todo.title = title;
        return todo;
      })
    );
    api.update(id, "", title).then((res) => {
      console.log("title change done", res);
    });
  }

  function handleCreation(title) {
    api.create(title).then((res) => {
      const newest = [...todos];
      newest.push(res);
      settodos(newest);
    });
  }

  return (
    <div className="card" style={{ width: "30rem" }}>
      <div className="card-header background-image"></div>
      <div className="card-body">
        <ul className="list-group">
          <li className="list-group-item active">
            Hello {username} these are your todos for today
          </li>
          <span className="todo-items">
            {todos.map((todo) => {
              return (
                <Item
                  key={todo._id}
                  id={todo._id}
                  isComplete={todo.completed}
                  title={todo.title}
                  handleDelete={handleDelete}
                  handleStatusChange={handleStatusChange}
                  handleTitleChange={handleTitleChange}
                />
              );
            })}
          </span>
          <Add handleCreation={handleCreation} />
        </ul>
      </div>
    </div>
  );
}

// client/vue-front/src/pages/Todo.vue
<template>
  <div class="card">
    <div class="card-header background-image"></div>
    <div class="card-body">
      <ul class="list-group">
        <li class="list-group-item active">Hello {{name}} these are your todos for today</li>
        <span class="todo-items">
          <item v-for="todo in todos" :key="todo._id" :todo="todo" @delete="onDelete" />
        </span>
        <add @created="onCreate"></add>
      </ul>
    </div>
  </div>
</template>

<script>
import item from "../components/Item.vue";
import add from "../components/Add.vue";
import api from "../api";
export default {
  name: "stranger",
  components: {
    item,
    add
  },
  methods: {
    onDelete(id) {
      this.todos = this.todos.filter(todo => todo._id !== id);
    },
    onCreate(todo) {
      console.log(todo, "cre");
      this.todos.push(todo);
    }
  },
  data() {
    return {
      todos: []
    };
  },
  created() {
    api
      .getAll()
      .then(res => {
        console.log(res);
        this.todos = res.todos;
      })
      .catch(err => console.log("err", err));
  }
};
</script>

<style>
.card {
  width: 30rem;
}

.background-image {
  height: 200px;
  background-image: url("https://mdbootstrap.com/img/Photos/Horizontal/Nature/full%20page/img(20).jpg");
  background-size: cover;
  background-repeat: no-repeat;
}
.todo-items {
  max-height: 30vh;
  overflow-y: scroll;
  min-height: 30vh;
}

li.list-group-item.active {
  background-color: #54a041;
  border-color: #54a041;
}
</style>
