// client/vue-front/src/components/Add.vue
<template>
  <li class="list-group-item">
    <div class="input-group input-group-sm mb-3">
      <div class="input-group-prepend">
        <input
          type="text"
          id="input"
          v-model="title"
          placeholder="Add todo"
          class="form-control"
          aria-describedby="inputGroup-sizing-sm"
        />
        <span class="input-group-text" id="inputGroup-sizing-sm">
          <i class="fa fa-plus-circle" v-on:click="handleCreation"></i>
        </span>
      </div>
    </div>
  </li>
</template>

<script type="text/javascript">
import api from "../api";
export default {
  name: "add",
  data() {
    return {
      title: ""
    };
  },
  methods: {
    handleCreation: function() {
      api.create(this.title).then(todo => {
        this.title = "";
        this.$emit("created", todo);
      });
    }
  }
};
</script>
<style>
</style>

// client/react-front/src/components/Add.jsx
import React, { useState } from "react";

export default function Add({ handleCreation }) {
  const [title, setTitle] = useState("");
  return (
    <li className="list-group-item">
      <div className="input-group input-group-sm mb-3">
        <div className="input-group-prepend">
          <input
            aria-describedby="inputGroup-sizing-sm"
            type="text"
            id="input"
            className="form-control"
            placeholder="new todo"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <span className="input-group-text" id="inputGroup-sizing-sm">
            add{" "}
            <i
              className="fa fa-plus-circle"
              onClick={(e) => {
                if (title.length > 2) handleCreation(title);
              }}
            ></i>
          </span>
        </div>
      </div>
    </li>
  );
}
