// client/angular-front/src/app/components/login/login.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { FormControl } from '@angular/forms';
import { AuthorizationService } from "../../services/authorization.service";
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  email = new FormControl('');
  password = new FormControl('');
  @Output() loginSwitch: EventEmitter<boolean> = new EventEmitter();
  constructor(private authorizationService: AuthorizationService, private router: Router) { }

  ngOnInit(): void {
  }


  switchLogin() {
    this.loginSwitch.emit(false)
  }

  login() {
    this.authorizationService.login(this.email.value, this.password.value).subscribe(res => {
      console.log(res.user, 'res');
      this.router.navigate(['/todos']);
    })
  }
}

<div class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal marge">Please sign in</h1>
    <input [formControl]="email" name="email" type="email" class="form-control marge" placeholder="Email address" />
    <input [formControl]="password" name="password" type="password" class="form-control marge" placeholder="Password" />
    <button (click)="login()" class="btn btn-lg btn-danger btn-block marge">Sign in</button>
    <span class="text-primary marge" (click)="switchLogin()">make an account</span>
</div>

// client/react-front/src/components/Login.jsx
import React, { useState } from "react";
import api from "../api/authorization";
import { withRouter } from "react-router-dom";

function Login(props) {
  const [profileInfo, setProfileInfo] = useState({
    email: "",
    password: "",
  });

  function handleChange(e) {
    const name = e.target.name;
    const value = e.target.value;
    setProfileInfo({ ...profileInfo, [name]: value });
  }

  function handleLogin(e) {
    e.preventDefault();
    api
      .login(profileInfo.email, profileInfo.password)
      .then((user) => {
        props.setUser(user);
        console.log("user", user);
        props.history.push("/todos");
      })
      .catch((err) => console.log("err", err));
  }

  return (
    <form className="form-signin">
      <h1 className="h3 mb-3 font-weight-normal" style={{ margin: "5px" }}>
        Please sign in
      </h1>
      <input
        name="email"
        type="email"
        onChange={handleChange}
        value={profileInfo.email}
        className="form-control"
        placeholder="Email address"
        style={{ margin: "5px" }}
      />
      <input
        name="password"
        type="password"
        onChange={handleChange}
        value={profileInfo.password}
        className="form-control"
        placeholder="Password"
        style={{ margin: "5px" }}
      />
      <button
        className="btn btn-lg btn-primary btn-block"
        onClick={handleLogin}
        type="submit"
        style={{ margin: "5px" }}
      >
        Sign in
      </button>
      <span
        onClick={() => props.setIsLogin(false)}
        className="text-primary"
        style={{ margin: "5px" }}
      >
        make an account
      </span>
    </form>
  );
}

export default withRouter(Login);
