// client/angular-front/src/app/components/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthorizationService } from "../../services/authorization.service";
import { Router } from '@angular/router';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit {
  user: Object = null
  constructor(private authorizationService: AuthorizationService, private router: Router) {
    this.authorizationService.userInfo.subscribe(res => {
      this.user = res.user
    })
  }

  ngOnInit(): void {
  }

  logout() {
    this.user = null
    this.router.navigate(['/home']);
  }

}

<div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">
      <i class="fas fa-clipboard-list"></i>
    </a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="link" href="#" routerLink="home">home</a>
        </li>
        <li *ngIf="user" class="nav-item">
          <a class="link" href="#" routerLink="todos">todos</a>
        </li>
      </ul>
      <button class="btn btn-danger my-2 my-sm-0">
        <a class="nav-link button" href="#" routerLink="authorization" *ngIf="!user">sign up / log in</a>
        <a class="nav-link button" routerLink="home" *ngIf="user" (click)="logout()">Logout</a>
      </button>
    </div>
  </nav>
  <ng-content></ng-content>

</div>

// client/react-front/src/components/Navigation.jsx
import React from "react";
import { Link } from "react-router-dom";

export default function Navigation({ user, children }) {
  return (
    <nav className="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a className="navbar-brand" href="#">
        <i className="fas fa-clipboard-list"></i>
      </a>
      <button
        className="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span className="navbar-toggler-icon"></span>
      </button>
      <div className="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul className="navbar-nav mr-auto mt-2 mt-lg-0">
          <li className="nav-item active">
            <Link className="link nav-link" to="/">
              home
            </Link>
          </li>
          {user && (
            <li className="nav-item">
              <Link className="link nav-link" to="/todos">
                todos
              </Link>
            </li>
          )}
        </ul>
        {!user && (
          <button className="btn btn-primary my-2 my-sm-0" type="submit">
            <Link
              className="link nav-link"
              style={{ color: "white" }}
              to="/authorization"
            >
              sign in / log in
            </Link>
          </button>
        )}
        {children}
      </div>
    </nav>
  );
}
