// client/react-front/src/components/Add.jsx
import React, { useState } from "react";

export default function Add({ handleCreation }) {
  const [title, setTitle] = useState("");
  return (
    <li className="list-group-item">
      <div className="input-group input-group-sm mb-3">
        <div className="input-group-prepend">
          <input
            aria-describedby="inputGroup-sizing-sm"
            type="text"
            id="input"
            className="form-control"
            placeholder="new todo"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <span className="input-group-text" id="inputGroup-sizing-sm">
            add{" "}
            <i
              className="fa fa-plus-circle"
              onClick={(e) => {
                if (title.length > 2) handleCreation(title);
              }}
            ></i>
          </span>
        </div>
      </div>
    </li>
  );
}

// client/angular-front/src/app/components/add/add.component.ts
import { Component, Output, EventEmitter } from "@angular/core";
import { TodoService } from "../../services/todo.service";
import { FormControl } from "@angular/forms";

@Component({
  selector: "app-add",
  templateUrl: "./add.component.html",
})
export class AddComponent {
  todo = new FormControl("");
  @Output() add: EventEmitter<any> = new EventEmitter();
  constructor(private todoservice: TodoService) { }

  addTodo() {
    console.log("creating", this.todo.value);
    this.todoservice.create(this.todo.value, false).subscribe((res) => {
      this.add.emit(res);
    });
    console.log("done");
  }
}

<li class="list-group-item">
  <div class="input-group input-group-sm mb-3">
    <div class="input-group-prepend">
      <input type="text" id="input" placeholder="Add todo" [formControl]="todo" class="form-control" />
      <span class="input-group-text" id="inputGroup-sizing-sm">
        <i class="fa fa-plus-circle" (click)="addTodo()"></i>
      </span>
    </div>
  </div>
</li>
