// client/react-front/src/components/Login.jsx
import React, { useState } from "react";
import api from "../api/authorization";
import { withRouter } from "react-router-dom";

function Login(props) {
  const [profileInfo, setProfileInfo] = useState({
    email: "",
    password: "",
  });

  function handleChange(e) {
    const name = e.target.name;
    const value = e.target.value;
    setProfileInfo({ ...profileInfo, [name]: value });
  }

  function handleLogin(e) {
    e.preventDefault();
    api
      .login(profileInfo.email, profileInfo.password)
      .then((user) => {
        props.setUser(user);
        console.log("user", user);
        props.history.push("/todos");
      })
      .catch((err) => console.log("err", err));
  }

  return (
    <form className="form-signin">
      <h1 className="h3 mb-3 font-weight-normal" style={{ margin: "5px" }}>
        Please sign in
      </h1>
      <input
        name="email"
        type="email"
        onChange={handleChange}
        value={profileInfo.email}
        className="form-control"
        placeholder="Email address"
        style={{ margin: "5px" }}
      />
      <input
        name="password"
        type="password"
        onChange={handleChange}
        value={profileInfo.password}
        className="form-control"
        placeholder="Password"
        style={{ margin: "5px" }}
      />
      <button
        className="btn btn-lg btn-primary btn-block"
        onClick={handleLogin}
        type="submit"
        style={{ margin: "5px" }}
      >
        Sign in
      </button>
      <span
        onClick={() => props.setIsLogin(false)}
        className="text-primary"
        style={{ margin: "5px" }}
      >
        make an account
      </span>
    </form>
  );
}

export default withRouter(Login);

// client/vue-front/src/components/Login.vue
<template>
  <form class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal marge">Please sign in</h1>
    <input
      name="email"
      type="email"
      v-model="email"
      class="form-control marge"
      placeholder="Email address"
    />
    <input
      name="password"
      type="password"
      v-model="password"
      class="form-control marge"
      placeholder="Password"
    />
    <button class="btn btn-lg btn-success btn-block marge" v-on:click="login" type="submit">Sign in</button>
    <span class="text-primary marge" v-on:click="switchLogin">make an account</span>
  </form>
</template>

<script type="text/javascript">
import api from "../authorization";
export default {
  name: "login",
  data() {
    return {
      email: "",
      password: ""
    };
  },
  methods: {
    switchLogin() {
      this.$emit("switchLogin", false);
    },
    login(event) {
      event.preventDefault();
      api
        .login(this.email, this.password)
        .then(user => {
          console.log(user);
          this.$emit("user", user);
          this.$router.push("todos");
        })
        .catch(err => console.log("err", err));
    }
  }
};
</script>
<style>
.header {
  width: 380px;
  height: 200px;
  background-image: url("https://mdbootstrap.com/img/Photos/Horizontal/Nature/full%20page/img(20).jpg");
  background-size: cover;
  background-repeat: no-repeat;
  border-radius: 15px 15px 0 0;
  position: relative;
}
.clear {
  width: 30px;
  height: 30px;
  position: absolute;
  right: 20px;
  top: 20px;
}
.clear i {
  font-size: 30px;
  color: #fff;
}
.clear i:hover {
  cursor: pointer;
  text-shadow: 1px 3px 5px #000;
  transform: rotate(45deg);
}
.marge {
  margin: 5px;
}
</style>
