// client/react-front/src/components/Signup.jsx
import React, { useState } from "react";
import api from "../api/authorization";
import { withRouter } from "react-router-dom";

function Signup(props) {
  const [profileInfo, setProfileInfo] = useState({
    name: "",
    email: "",
    password: "",
  });

  function handleChange(e) {
    const name = e.target.name;
    const value = e.target.value;
    setProfileInfo({ ...profileInfo, [name]: value });
  }

  function handleSignIn(e) {
    e.preventDefault();
    api
      .signup(profileInfo.name, profileInfo.email, profileInfo.password)
      .then((user) => {
        props.setUser(user);
        props.history.push("/todos");
      })
      .catch((err) => console.log("err", err));
  }

  return (
    <form className="form-signin">
      <h1 className="h3 mb-3 font-weight-normal" style={{ margin: "5px" }}>
        Hello welcome to sign up
      </h1>
      <input
        name="name"
        type="text"
        onChange={handleChange}
        value={profileInfo.name}
        className="form-control"
        placeholder="Name"
        style={{ margin: "5px" }}
      />
      <input
        name="email"
        type="email"
        onChange={handleChange}
        value={profileInfo.email}
        className="form-control"
        placeholder="Email address"
        style={{ margin: "5px" }}
      />
      <input
        name="password"
        type="password"
        onChange={handleChange}
        value={profileInfo.password}
        className="form-control"
        placeholder="Password"
        style={{ margin: "5px" }}
      />
      <button
        className="btn btn-lg btn-primary btn-block"
        onClick={handleSignIn}
        style={{ margin: "5px" }}
      >
        Sign up
      </button>
      <a
        onClick={() => props.setIsLogin(true)}
        className="text-primary"
        style={{ margin: "5px" }}
      >
        I already have an account
      </a>
      <p className="mt-5 mb-3 text-muted">© 2019-2020</p>
    </form>
  );
}

export default withRouter(Signup);

// client/vue-front/src/components/Signup.vue
<template>
  <form class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal marge">Hello welcome to sign up</h1>
    <input name="name" type="text" v-model="name" class="form-control marge" placeholder="name" />
    <input
      name="email"
      type="email"
      v-model="email"
      class="form-control marge"
      placeholder="Email address"
    />
    <input
      name="password"
      type="password"
      v-model="password"
      class="form-control marge"
      placeholder="Password"
    />
    <button class="btn btn-lg btn-success btn-block marge" v-on:click="signup" type="submit">Sign up</button>
    <span class="text-primary marge" v-on:click="switchLogin">I already have an account</span>
  </form>
</template>

<script type="text/javascript">
import api from "../authorization";
export default {
  name: "signup",
  data() {
    return {
      name: "",
      email: "",
      password: ""
    };
  },
  methods: {
    switchLogin() {
      this.$emit("switchLogin", true);
    },
    signup(event) {
      event.preventDefault();
      api
        .signup(this.name, this.email, this.password)
        .then(user => {
          // this.$emit("user", user);
          console.log(user);

          this.$router.replace({ name: "todos" });
        })
        .catch(err => console.log("err", err));
    }
  }
};
</script>
<style>
.header {
  width: 380px;
  height: 200px;
  background-image: url("https://mdbootstrap.com/img/Photos/Horizontal/Nature/full%20page/img(20).jpg");
  background-size: cover;
  background-repeat: no-repeat;
  border-radius: 15px 15px 0 0;
  position: relative;
}
.clear {
  width: 30px;
  height: 30px;
  position: absolute;
  right: 20px;
  top: 20px;
}
.clear i {
  font-size: 30px;
  color: #fff;
}
.clear i:hover {
  cursor: pointer;
  text-shadow: 1px 3px 5px #000;
  transform: rotate(45deg);
}
.marge {
  margin: 5px;
}
</style>
