// client/react-front/src/pages/Todo.jsx
import React, { useState, useEffect } from "react";
import "../styles/todo.css";
import api from "../api/todo";
import Header from "../components/Header";
import Add from "../components/Add";
import Item from "../components/Item";

export default function Todo() {
  const [todos, settodos] = useState([]);
  useEffect(() => {
    const res = api.getAll().then((_todos) => {
      console.log("_todos", _todos);
      settodos(_todos.todos);
    });

    return () => {};
  }, []);

  function handleDelete(id) {
    console.log("id", id);
    api.delete(id).then((res) => {
      console.log("delete done", res);
      settodos(todos.filter((todo) => todo._id !== id));
    });
  }

  function handleStatusChange(id, status) {
    settodos(
      todos.map((todo) => {
        if (todo._id === id) todo.completed = !todo.completed;
        return todo;
      })
    );
    api.update(id, status, "").then((res) => {
      console.log("status change done", res);
    });
  }

  function handleTitleChange(id, title) {
    settodos(
      todos.map((todo) => {
        if (todo._id === id) todo.title = title;
        return todo;
      })
    );
    api.update(id, "", title).then((res) => {
      console.log("title change done", res);
    });
  }

  function handleCreation(title) {
    api.create(title).then((res) => {
      const newest = [...todos];
      newest.push(res);
      settodos(newest);
    });
  }

  return (
    <div className="container">
      <Header />
      <div className="content">
        <ul id="list">
          {todos.map((todo) => {
            return (
              <Item
                key={todo._id}
                id={todo._id}
                isComplete={todo.completed}
                title={todo.title}
                handleDelete={handleDelete}
                handleStatusChange={handleStatusChange}
                handleTitleChange={handleTitleChange}
              />
            );
          })}
        </ul>
      </div>
      <Add handleCreation={handleCreation} />
    </div>
  );
}

// client/angular-front/src/app/pages/todo/todo.component.ts
import { Component, OnInit } from "@angular/core";
import { TodoService } from "../../services/todo.service";
import { Todo } from "../../models/Todo";

@Component({
  selector: "app-todo",
  templateUrl: "./todo.component.html",
  styleUrls: ["./todo.component.css"],
})
export class TodoComponent implements OnInit {
  todos: Todo[];
  constructor(private todoservice: TodoService) {}

  ngOnInit(): void {
    this.todoservice.getAll().subscribe((res) => {
      console.log("res", res);
      this.todos = res.todos;
    });
  }

  onAdd({ todo }) {
    this.todos.push(todo);
  }

  onDelete({ todo: { _id } }) {
    this.todos = this.todos.filter((todo) => todo._id !== _id);
  }

  onChange({ todo: { _id, title, completed } }) {
    this.todos = this.todos.map((todo) => {
      if (todo._id === _id) {
        todo.completed = completed;
        todo.title = title;
        console.log("todo", todo);
      }
      return todo;
    });
  }
}

<div class="container">
  <div class="header">
    <div class="clear">
      <i class="fa fa-refresh"></i>
    </div>
    <div id="date"></div>
  </div>
  <div class="content">
    <ul id="list">
      <li *ngFor="let todo of todos">
        <app-item
          [todo]="todo"
          (delete)="onDelete($event)"
          (change)="onChange($event)"
        ></app-item>
      </li>
    </ul>
  </div>
  <app-add (add)="onAdd($event)"></app-add>
</div>
